ImThreshold.
0.20190220

Download
--------

The latest stable version of this library can be downloaded from:
https://sourceforge.net/projects/imthreshold/

Dependencies
------------

Depends this library:

  freeimage

Build
-----

To build this library type the following:

  cd [imthreshold/source/path]
  make

Test
----

To test this library type the following:

  cd [imthreshold/source/path]
  LD_LIBRARY_PATH=. ./imthreshold-[utils] <image_in> <image_out>

Installation
------------

To install this library type the following:

  cd [imthreshold/source/path]
  sudo make install

Copyright and licence
---------------------

This program is free software;
You can redistribute it and/or
modify it under the terms of the Zlib License.

Copyright (C) 2016-2019 zvezdochiot.
