.TH "ImThreshold User Manual" 1 "19 Dec 2017" "ImThreshold documentation"

.SH NAME
imthreshold-sbwmag2

.SH DESCRIPTION
Magnification BW image.

.SH SYNOPSIS
imthreshold-sbwmag2 [options] <input_file>(BW) <output_file>(BW)

.SH OPTIONS
.TP
-r
reduce (bool, optional, default = false)
.TP
-h
help

.SH EXAMPLE
 imthreshold-sbwmag2 sample.tif sample.mag2.tif
 imthreshold-sbwmag2 -r sample.mag2.tif sample.reduce.tif

.SH COPYRIGHT
Copyright 2017 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 imthreshold,
 imthreshold-anytodjvu,
 imthreshold-anytominidjvu,
 imthreshold-deskew,
 imthreshold-fautoinv,
 imthreshold-fbgfglsep,
 imthreshold-fdespeckle,
 imthreshold-filter,
 imthreshold-finfo,
 imthreshold-flevell,
 imthreshold-fpmean,
 imthreshold-rotate,
 imthreshold-sbwmag2,
 imthreshold-scris,
 imthreshold-shris,
 imthreshold-size,
 imthreshold-tdalg,
 imthreshold-tdjvul,
 imthreshold-tgatos,
 imthreshold-tglobal,
 imthreshold-thalftone2,
 imthreshold-tlocal,
 imthreshold-ttext,
 imthreshold-twhiterohrer,
 imthreshold-bash-scripts.

.SH CONTACTS
BookScanLib Project:
 Website: http://djvu-soft.narod.ru/

Imthreshold Project:
 Website: https://sourceforge.net/projects/imthreshold/
 Email: zvezdochiot@users.sourceforge.net
