.TH "ImThreshold" 1 0.20200307 "07 Mar 2020" "User Manual"

.SH NAME
imthreshold-shris

.SH DESCRIPTION
Half Reverse Interpolate Scale image (HRIS).
Zoom in / out 2 times a specially optimized scheme.

.SH SYNOPSIS
imthreshold-shris [options] <input_file> <output_file>

.SH OPTIONS
.TP
-f str
name filter:
    'hris' (default)
    'gsample'
    'frp' (long!)
.TP
-m
mode (int, optional, default = 2, {2,{3(hris),all(gsample)}})
.TP
-r
reduce scale (bool, optional)
.TP
-h
help

.SH EXAMPLE
 imthreshold-shris sample.tif sample.hris.tif
 imthreshold-shris -r sample.hris.tif sample.reduce.tif

.SH COPYRIGHT
Copyright 2017 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 imthreshold,
 imthreshold-a4,
 imthreshold-anytodjvu,
 imthreshold-anytominidjvu,
 imthreshold-deskew,
 imthreshold-fautoinv,
 imthreshold-fdespeckle,
 imthreshold-filter,
 imthreshold-finfo,
 imthreshold-fpmean,
 imthreshold-math,
 imthreshold-rotate,
 imthreshold-sbwmag2,
 imthreshold-scris,
 imthreshold-separate,
 imthreshold-shris,
 imthreshold-size,
 imthreshold-tdalg,
 imthreshold-tdjvul,
 imthreshold-tgatos,
 imthreshold-tglobal,
 imthreshold-thalftone2,
 imthreshold-tlayer,
 imthreshold-tlocal,
 imthreshold-ttext,
 imthreshold-twhiterohrer,
 imthreshold-bash-scripts.

.SH CONTACTS
BookScanLib Project:
 Website: http://djvu-soft.narod.ru/

Imthreshold Project:
 Website: https://sourceforge.net/projects/imthreshold/
 Email: zvezdochiot@users.sourceforge.net
