.TH "ImThreshold" 1 0.20230428 "28 Apr 2023" "User Manual"

.SH NAME
imthreshold-tglobal

.SH DESCRIPTION
Global thresholding image.

.SH SYNOPSIS
imthreshold-tglobal [options] <input_image> <output_image>(BW)

.SH OPTIONS
.TP
-b
color correct (bool, optional, default = false)
.TP
-d N
delta (int, optional, default = 0)
.TP
-f str
name filter:
    'bayer'
    'bht'
    'bimod' (default)
    'bimodc'
    'color'
    'dither'
    'dithk' (Knuth D.E.)
    'dots'
    'entropy'
    'eqbright'
    'grad'
    'janni'
    'kmeans'
    'otsu'
    'quadmod'
    'rot'
    'tsai'
    'use' (T=127)
.TP
-i
invert (bool, optional, default = false)
.TP
-k N
K par (k/2) (int, optional, default = 1)
.TP
-m N
max iteration (int, optional, default = 10)
.TP
-n
norm (bool, optional, default = false)
.TP
-p N
pattern (int, optional, default = 4)
.TP
-q str
colorspace:
    'rgb' (default)
    'ryb4'
    'ycbcr'
    'hsv'
.TP
-s N
shift (int, optional, default = -32)
.TP
-w
weight colors (bool, optional)
.TP
-z
mirror of mean (bool, optional, default = false)
.TP
-h
help

.SH EXAMPLE
imthreshold-tglobal -f grad sample.tif sample.tglobal.tif

.SH COPYRIGHT
Copyright 2017 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 imthreshold,
 imthreshold-a4,
 imthreshold-anytodjvu,
 imthreshold-anytominidjvu,
 imthreshold-deskew,
 imthreshold-fautoinv,
 imthreshold-fdespeckle,
 imthreshold-filter,
 imthreshold-finfo,
 imthreshold-fpmean,
 imthreshold-math,
 imthreshold-rotate,
 imthreshold-sbwmag2,
 imthreshold-scris,
 imthreshold-separate,
 imthreshold-shris,
 imthreshold-size,
 imthreshold-tdalg,
 imthreshold-tdjvul,
 imthreshold-tgatos,
 imthreshold-tglobal,
 imthreshold-thalftone2,
 imthreshold-tlayer,
 imthreshold-tlocal,
 imthreshold-ttext,
 imthreshold-twhiterohrer,
 imthreshold-bash-scripts.

.SH CONTACTS
BookScanLib Project:
 Website: http://djvu-soft.narod.ru/

Imthreshold Project:
 Website: https://sourceforge.net/projects/imthreshold/
 Email: zvezdochiot@users.sourceforge.net
