.TH "ImThreshold" 1 0.20230320 "20 Mar 2023" "User Manual"

.SH NAME
imthreshold-twhiterohrer

.SH DESCRIPTION
White Rohrer thresholding image.
 This algorithm was taken from the gamera.sf.net sourcecodes and adopted for the FreeImage library.

.SH SYNOPSIS
imthreshold-twhiterohrer [options] <input_file> <output_file>(BW)

.SH OPTIONS
.TP
-x N
x lookahead (int, optional, default = 8)
.TP
-y N
y lookahead (int, optional, default = 1)
.TP
-m N
bias mode (int, optional, default = 0)
.TP
-b N
bias factor (int, optional, default = 50)
.TP
-f N
f factor (int, optional, default = 50)
.TP
-g N
g factor (int, optional, default = 50)
.TP
-h
help

.SH EXAMPLE
imthreshold-twhiterohrer sample.tif sample.bw.whiterohrer.tif

.SH COPYRIGHT
Copyright 2017 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 imthreshold,
 imthreshold-a4,
 imthreshold-anytodjvu,
 imthreshold-anytominidjvu,
 imthreshold-deskew,
 imthreshold-fautoinv,
 imthreshold-fdespeckle,
 imthreshold-filter,
 imthreshold-finfo,
 imthreshold-fpmean,
 imthreshold-math,
 imthreshold-rotate,
 imthreshold-sbwmag2,
 imthreshold-scris,
 imthreshold-separate,
 imthreshold-shris,
 imthreshold-size,
 imthreshold-tdalg,
 imthreshold-tdjvul,
 imthreshold-tgatos,
 imthreshold-tglobal,
 imthreshold-thalftone2,
 imthreshold-tlayer,
 imthreshold-tlocal,
 imthreshold-ttext,
 imthreshold-twhiterohrer,
 imthreshold-bash-scripts.

.SH CONTACTS
BookScanLib Project:
 Website: http://djvu-soft.narod.ru/

Imthreshold Project:
 Website: https://sourceforge.net/projects/imthreshold/
 Email: zvezdochiot@users.sourceforge.net
