.TH "ImThreshold User Manual" 1 "13 Oct 2019" "ImThreshold documentation"

.SH NAME
imthreshold-ttext

.SH DESCRIPTION
Text thresholding image.

.SH SYNOPSIS
imthreshold-ttext [options] <input_file> <output_file>(BW) [textg_file]

.SH OPTIONS
.TP
-c N
contour amplitude (int, optional, default = 5)
.TP
-r N
radius (int, optional, default = 5)
.TP
-h
help

.SH EXAMPLE
imthreshold-ttext sample.tif sample.bw.text.tif

.SH COPYRIGHT
Copyright 2017 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 imthreshold,
 imthreshold-a4,
 imthreshold-anytodjvu,
 imthreshold-anytominidjvu,
 imthreshold-deskew,
 imthreshold-fautoinv,
 imthreshold-fdespeckle,
 imthreshold-filter,
 imthreshold-finfo,
 imthreshold-fpmean,
 imthreshold-math,
 imthreshold-rotate,
 imthreshold-sbwmag2,
 imthreshold-scris,
 imthreshold-separate,
 imthreshold-shris,
 imthreshold-size,
 imthreshold-tdalg,
 imthreshold-tdjvul,
 imthreshold-tgatos,
 imthreshold-tglobal,
 imthreshold-thalftone2,
 imthreshold-tlayer,
 imthreshold-tlocal,
 imthreshold-ttext,
 imthreshold-twhiterohrer,
 imthreshold-bash-scripts.

.SH CONTACTS
BookScanLib Project:
 Website: http://djvu-soft.narod.ru/

Imthreshold Project:
 Website: https://sourceforge.net/projects/imthreshold/
 Email: zvezdochiot@users.sourceforge.net
