.TH "ImThreshold" 1 0.20230707 "07 Jul 2023" "User Manual"

.SH NAME
 imthreshold-fpmean

.SH DESCRIPTION
PMean filter image.
 (denoise)

.SH SYNOPSIS
imthreshold-fpmean [options] <input_file> <output_file>

.SH OPTIONS
.TP
-m str
mode
(string, optional):
    similar (default),
    nlm,
    bilateral,
    wbselect,
    radial,
    simple,
    minmax.
.TP
-n
neared (bool, optional, default = false)
.TP
-q str
colorspace:
(string, optional):
    'rgb' (default),
    'ryb4',
    'ycbcr'.
    'hsv'.
.TP
-r N.N
radius (float, optional, default = 3.0)
.TP
-h
help

.SH EXAMPLE
imthreshold-fpmean sample.tif sample.pmean.tif

.SH COPYRIGHT
Copyright 2017 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 imthreshold,
 imthreshold-a4,
 imthreshold-anytodjvu,
 imthreshold-anytominidjvu,
 imthreshold-deskew,
 imthreshold-fautoinv,
 imthreshold-fdespeckle,
 imthreshold-filter,
 imthreshold-finfo,
 imthreshold-fpmean,
 imthreshold-math,
 imthreshold-rotate,
 imthreshold-sbwmag2,
 imthreshold-scris,
 imthreshold-separate,
 imthreshold-shris,
 imthreshold-size,
 imthreshold-tdalg,
 imthreshold-tdjvul,
 imthreshold-tgatos,
 imthreshold-tglobal,
 imthreshold-thalftone2,
 imthreshold-tlayer,
 imthreshold-tlocal,
 imthreshold-ttext,
 imthreshold-twhiterohrer,
 imthreshold-bash-scripts.

.SH CONTACTS
BookScanLib Project:
 Website: http://djvu-soft.narod.ru/

Imthreshold Project:
 Website: https://sourceforge.net/projects/imthreshold/
 Email: zvezdochiot@users.sourceforge.net
