.TH "ImThreshold" 1 0.20230704 "04 Jul 2023" "User Manual"

.SH NAME
imthreshold-separate

.SH DESCRIPTION
Separate image.

.SH SYNOPSIS
imthreshold-separate [options] <input_file> <input_mask_file>(BW) <output_fg_file> <output_bg_file>

.SH OPTIONS
.TP
-b N
base block size (int, optional, default = 3)
.TP
-c N
clean blur radius (int, optional, default = 0)
.TP
-f N
foreground divide (int, optional, default = 2)
.TP
-k N.N
coefficient delta threshold (float, optional, default = 2.0)
.TP
-l N
level (int, optional, default = 0[auto])
.TP
-m str
name method:
                    'delta'
                    'inpaint'
                    'mscale'
                    'simple' (default)
.TP
-o N.N
overlay (float, optional, default = 0.5)
.TP
-r
rewrite mask (bool, optional, default = false)
.TP
-h
help

.SH EXAMPLE
imthreshold-separate input.png input.bw.tif output.fg.png output.bg.png

.SH COPYRIGHT
Copyright 2017 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 imthreshold,
 imthreshold-a4,
 imthreshold-anytodjvu,
 imthreshold-anytominidjvu,
 imthreshold-deskew,
 imthreshold-fautoinv,
 imthreshold-fdespeckle,
 imthreshold-filter,
 imthreshold-finfo,
 imthreshold-fpmean,
 imthreshold-math,
 imthreshold-rotate,
 imthreshold-sbwmag2,
 imthreshold-scris,
 imthreshold-separate,
 imthreshold-shris,
 imthreshold-size,
 imthreshold-tdalg,
 imthreshold-tdjvul,
 imthreshold-tgatos,
 imthreshold-tglobal,
 imthreshold-thalftone2,
 imthreshold-tlayer,
 imthreshold-tlocal,
 imthreshold-ttext,
 imthreshold-twhiterohrer,
 imthreshold-bash-scripts.

.SH CONTACTS
BookScanLib Project:
 Website: http://djvu-soft.narod.ru/

Imthreshold Project:
 Website: https://sourceforge.net/projects/imthreshold/
 Email: zvezdochiot@users.sourceforge.net
