.TH "ImThreshold" 1 0.20210430 "30 Apr 2021" "User Manual"

.SH NAME
imthreshold-anytodjvu

.SH DESCRIPTION
The bash script creates a djvu-file from a color image. Uses netpbm, DjVuL and djvulibre.

.SH SYNOPSIS
imthreshold-anytodjvu [options] image

.SH OPTIONS
.TP
-a N.N
anisotropic (default = 0.0)
.TP
-c N
despeckle clean (default = 0);
.TP
-d N
dpi (default = 300);
.TP
-o Name
output file (default = imagename.djvu);
.TP
-h
help

.SH EXAMPLE
imthreshold-anytodjvu sample.tif

.SH COPYRIGHT
Copyright 2016 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 imthreshold,
 imthreshold-a4,
 imthreshold-anytodjvu,
 imthreshold-anytominidjvu,
 imthreshold-deskew,
 imthreshold-fautoinv,
 imthreshold-fdespeckle,
 imthreshold-filter,
 imthreshold-finfo,
 imthreshold-fpmean,
 imthreshold-math,
 imthreshold-rotate,
 imthreshold-sbwmag2,
 imthreshold-scris,
 imthreshold-separate,
 imthreshold-shris,
 imthreshold-size,
 imthreshold-tdalg,
 imthreshold-tdjvul,
 imthreshold-tgatos,
 imthreshold-tglobal,
 imthreshold-thalftone2,
 imthreshold-tlayer,
 imthreshold-tlocal,
 imthreshold-ttext,
 imthreshold-twhiterohrer,
 imthreshold-bash-scripts.

.SH CONTACTS
BookScanLib Project:
 Website: http://djvu-soft.narod.ru/

Imthreshold Project:
 Website: https://sourceforge.net/projects/imthreshold/
 Email: zvezdochiot@users.sourceforge.net

