.TH "ImThreshold" 1 0.20221221 "21 Dec 2022" "User Manual"

.SH NAME
imthreshold-filter

.SH DESCRIPTION
Filter image.

.SH SYNOPSIS
imthreshold-filter [options] <input_image> <output_image>

.SH OPTIONS
.TP
-a N.N
amount (float, optional, default = 0.5)
.TP
-c N.N
contour factor (float, optional, default = -1[auto])
.TP
-d N
max delta (int, optional, default = 50)
.TP
-f str
name filter:
    'adsmooth'
    'bimod'
    'blur'
    'bwc'
    'cluster'
    'denoise'
    'greynorm'
    'greyworld'
    'illumc'
    'invert'
    'kmeans'
    'levelmean'
    'levelsigma'
    'levelsize'
    'mirror'
    'monocolor'
    'mbclose'
    'mbdilate'
    'mberose'
    'mbopen'
    'mclose'
    'mdilate'
    'merose'
    'mopen'
    'none' (default)
    'peron'
    'posterize'
    'retinex'
    'rs'
    'selgauss'
    'shrink'
    'unripple'
    'unsharp'
    'whitefill'
    'wiener'
.TP
-i N
num divide (int, optional, default = 1)
.TP
-k N
K num (int, optional, default = 2)
.TP
-l N
lower bound (int, optional, default = 32)
.TP
-n N.N
noise size (float, optional, default = -1.0[auto])
.TP
-p N
posterize divide factor (int, optional, default = 16)
.TP
-q str
colorspace:
    'rgb' (default)
    'ryb4'
    'ycbcr'
.TP
-r N.N
radius (float, optional, default = 3.0)
.TP
-s N.N
sigma (float, optional, default = 4.0)
.TP
-t N.N
threshold (float, optional, default = 0.0)
.TP
-u N
upper bound (int, optional, default = 223)
.TP
-h
help

.SH EXAMPLE
imthreshold-filter -f wiener sample.tif sample.filter.tif

.SH COPYRIGHT
Copyright 2017 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 imthreshold,
 imthreshold-a4,
 imthreshold-anytodjvu,
 imthreshold-anytominidjvu,
 imthreshold-deskew,
 imthreshold-fautoinv,
 imthreshold-fdespeckle,
 imthreshold-filter,
 imthreshold-finfo,
 imthreshold-fpmean,
 imthreshold-math,
 imthreshold-rotate,
 imthreshold-sbwmag2,
 imthreshold-scris,
 imthreshold-separate,
 imthreshold-shris,
 imthreshold-size,
 imthreshold-tdalg,
 imthreshold-tdjvul,
 imthreshold-tgatos,
 imthreshold-tglobal,
 imthreshold-thalftone2,
 imthreshold-tlayer,
 imthreshold-tlocal,
 imthreshold-ttext,
 imthreshold-twhiterohrer,
 imthreshold-bash-scripts.

.SH CONTACTS
BookScanLib Project:
 Website: http://djvu-soft.narod.ru/

Imthreshold Project:
 Website: https://sourceforge.net/projects/imthreshold/
 Email: zvezdochiot@users.sourceforge.net
