.TH "ImThreshold" 1 0.20200418 "18 Apr 2020" "User Manual"

.SH NAME
 imthreshold-math

.SH DESCRIPTION
Math opertion of two image.

.SH SYNOPSIS
imthreshold-math [options] <input_file> <input_file> <output_file>

.SH OPTIONS
.TP
-m str
name method
(string, optional, default = similar):
    'average'
    'distance'
    'divide'
    'geometric'
    'harmonic'
    'max'
    'min'
    'minus'
    'mirror'
    'multiply'
    'norm'
    'plus'
    'sbmetric'
    'threshold (default)'
.TP
-d N
delta (int, optional, default = 0)
.TP
-h
help

.SH EXAMPLE
imthreshold-math -m multiply sample1.tif sample2.tif sample.multiply.tif

.SH COPYRIGHT
Copyright 2017 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 imthreshold,
 imthreshold-a4,
 imthreshold-anytodjvu,
 imthreshold-anytominidjvu,
 imthreshold-deskew,
 imthreshold-fautoinv,
 imthreshold-fdespeckle,
 imthreshold-filter,
 imthreshold-finfo,
 imthreshold-fpmean,
 imthreshold-math,
 imthreshold-rotate,
 imthreshold-sbwmag2,
 imthreshold-scris,
 imthreshold-separate,
 imthreshold-shris,
 imthreshold-size,
 imthreshold-tdalg,
 imthreshold-tdjvul,
 imthreshold-tgatos,
 imthreshold-tglobal,
 imthreshold-thalftone2,
 imthreshold-tlayer,
 imthreshold-tlocal,
 imthreshold-ttext,
 imthreshold-twhiterohrer,
 imthreshold-bash-scripts.

.SH CONTACTS
BookScanLib Project:
 Website: http://djvu-soft.narod.ru/

Imthreshold Project:
 Website: https://sourceforge.net/projects/imthreshold/
 Email: zvezdochiot@users.sourceforge.net
