.TH "ImThreshold" 1 0.20230428 "28 Apr 2023" "User Manual"

.SH NAME
imthreshold-size

.SH DESCRIPTION
Resize image.

.SH SYNOPSIS
imthreshold-size [options] <input_image> <output_image>

.SH OPTIONS
.TP
-f str
name filter:
                    'biakima'
                    'bicont'
                    'bicubic'
                    'biline'
                    'gsample' (default)
                    'nearest'
.TP
-p N.N
part prefilter RIS (float, optional, default = 1.0)
(<0 - back-direct-diff/4-direct-patch, >0 - direct-back-diff-path-direct)
.TP
-q str
colorspace:
    'rgb' (default)
    'ryb4'
    'ycbcr'
    'hsv'
.TP
-r N.N
ratio, scale factor (float, optional, default = 1.0)
.TP
-w N
new width (int, optional, default = [auto])
.TP
-z N
new height (int, optional, default = [auto])
.TP
-h
help

.SH EXAMPLE
imthreshold-scris -r 0.5 sample.tif sample.cris.0_5.tif

.SH COPYRIGHT
Copyright 2017 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 imthreshold,
 imthreshold-a4,
 imthreshold-anytodjvu,
 imthreshold-anytominidjvu,
 imthreshold-deskew,
 imthreshold-fautoinv,
 imthreshold-fdespeckle,
 imthreshold-filter,
 imthreshold-finfo,
 imthreshold-fpmean,
 imthreshold-math,
 imthreshold-rotate,
 imthreshold-sbwmag2,
 imthreshold-scris,
 imthreshold-separate,
 imthreshold-shris,
 imthreshold-size,
 imthreshold-tdalg,
 imthreshold-tdjvul,
 imthreshold-tgatos,
 imthreshold-tglobal,
 imthreshold-thalftone2,
 imthreshold-tlayer,
 imthreshold-tlocal,
 imthreshold-ttext,
 imthreshold-twhiterohrer,
 imthreshold-bash-scripts.

.SH CONTACTS
BookScanLib Project:
 Website: http://djvu-soft.narod.ru/

Imthreshold Project:
 Website: https://sourceforge.net/projects/imthreshold/
 Email: zvezdochiot@users.sourceforge.net
