.TH "ImThreshold" 1 0.20200212 "12 Feb 2020" "User Manual"

.SH NAME
imthreshold-a4

.SH DESCRIPTION
The bash script resize image to size A4. Uses netpbm, HRIS and bicubic interpolation.

.SH SYNOPSIS
imthreshold-a4 [options] image

.SH OPTIONS
.TP
-d N
dpi (default = 300);
.TP
-o Name
output file (default = imagename-a4.tif);
.TP
-p N
PMean filter (default = 0 [none]);
.TP
-h
help

.SH EXAMPLE
imthreshold-a4 -d 450 sample.tif

.SH COPYRIGHT
Copyright 2016 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 imthreshold,
 imthreshold-a4,
 imthreshold-anytodjvu,
 imthreshold-anytominidjvu,
 imthreshold-deskew,
 imthreshold-fautoinv,
 imthreshold-fdespeckle,
 imthreshold-filter,
 imthreshold-finfo,
 imthreshold-fpmean,
 imthreshold-math,
 imthreshold-rotate,
 imthreshold-sbwmag2,
 imthreshold-scris,
 imthreshold-separate,
 imthreshold-shris,
 imthreshold-size,
 imthreshold-tdalg,
 imthreshold-tdjvul,
 imthreshold-tgatos,
 imthreshold-tglobal,
 imthreshold-thalftone2,
 imthreshold-tlayer,
 imthreshold-tlocal,
 imthreshold-ttext,
 imthreshold-twhiterohrer,
 imthreshold-bash-scripts.

.SH CONTACTS
BookScanLib Project:
 Website: http://djvu-soft.narod.ru/

Imthreshold Project:
 Website: https://sourceforge.net/projects/imthreshold/
 Email: zvezdochiot@users.sourceforge.net

